project:
  type: book
  # change output-dir to "docs" to publish to gh pages
  output-dir: docs

book:
  title: "Test Book"
  author: "Nic Jelinski"
  date: "11/13/2023"
  # cover-image: "open-science-badge.png"
  
  chapters:
    - index.qmd
    - chapter1.qmd
    - chapter2.qmd
    

# bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

